# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Activity.create!([
  { :project_id => 1, :name => "System design", :description => "Create UML diagrams for the system", :duration => 20, :finished => false, :created_at => "2014-11-02 17:35:08", :updated_at => "2014-11-02 17:35:08" },
  { :project_id => 1, :name => "Implementation", :description => "Implement the Rails web app, and Android app", :duration => nil, :finished => false, :created_at => "2014-11-02 19:09:55", :updated_at => "2014-11-02 19:09:55" }
])



Project.create!([
  { :name => "BP project", :short_description => "Project management and meeting scheduling tool", :long_description => nil, :start_date => "2014-11-02", :end_date => "2015-01-02", :duration => 20000, :member_count => 5, :budget => 0.0, :finished => false, :created_at => "2014-11-02 17:30:12", :updated_at => "2014-11-02 17:30:12" }
])



Role.create!([
  { :name => "Manager", :created_at => "2014-11-02 17:32:23", :updated_at => "2014-11-02 17:32:23" },
  { :name => "Member", :created_at => "2014-11-02 17:32:36", :updated_at => "2014-11-02 17:32:36" }
])



Task.create!([
  { :activity_id => 1, :user_id => 1, :name => "Create ERD diagram", :description => "Draw the initial DB tables and their relations", :duration => 3, :deadline => "2014-11-04", :status => 20.0, :real_duration => nil, :created_at => "2014-11-02 17:36:52", :updated_at => "2014-11-02 17:36:52" }
])



User.create!([
  { :name => "Sadzid", :surname => "Suljic", :email => "sadzid.etf@gmail.com", :username => "ssuljic", :password => "4073d3af798d33d05b5d3e356365e69a38021d322e57032882fee7be15ee6878", :created_at => "2014-11-02 17:30:43", :updated_at => "2014-11-02 17:30:43" }
])



UserProject.create!([
  { :user_id => 1, :project_id => 1, :role_id => 1, :number_of_hours => 4000, :created_at => "2014-11-02 17:33:41", :updated_at => "2014-11-02 17:33:41" }
])


